// ProvidersData.ts

export const providersData = [
  {
    id: "1",
    title: "Cool Choice",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "/services/Dine/Cool Choice/01.jpg",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "2",
    title: "Bobo Bohthalo",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "3",
    title: "Koba Chai",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "/services/Dine/Koba Chai/01.jpg",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "4",
    title: "SIS Forest",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "/services/Dine/SIS Forest/01.jpg",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "5",
    title: "Ashrafee Garden",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "6",
    title: "Second Home Restaurant",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "7",
    title: "Café Palato",
    slug: "dine",
    slugTitle: "Dine",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "8",
    title: "Dive Club Buoyancy",
    slug: "diving",
    slugTitle: "Diving",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "9",
    title: "Conquerors Excursions",
    slug: "excursion",
    slugTitle: "Excursion",
    description: "",
    image: "/services/excursion/Conquerors Excursions/01.PNG",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "10",
    title: "Mini Diamond",
    slug: "gifts-groceries",
    slugTitle: "Gifts & Groceries",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "11",
    title: "SU Corner",
    slug: "gifts-groceries",
    slugTitle: "Gifts & Groceries",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "12",
    title: "Irama Store",
    slug: "gifts-groceries",
    slugTitle: "Gifts & Groceries",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "13",
    title: "Arrival",
    slug: "gifts-groceries",
    slugTitle: "Gifts & Groceries",
    description: "",
    image: "/services/Gifts & Groceries/Arrival/01.jpg",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "14",
    title: "Haze Line",
    slug: "gifts-groceries",
    slugTitle: "Gifts & Groceries",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "15",
    title: "Kamana Spa",
    slug: "hair-dressing-makeup",
    slugTitle: "Hair Dressing & Makeup",
    description: "",
    image: "",
    phone: "",
    email: "",
    website: "",
  },
  {
    id: "16",
    title: "Captal Island Villa",
    slug: "stays",
    slugTitle: "Stays",
    description: "Hifaseyhavaadhee, Funagas Magu, Mathiveri",
    image: "/services/stay/captal/01.PNG",
    phone: "9982544",
    email: "captalislandvilla@gmail.com",
    website: "facebook.com/captalislandvilla",
  },
  {
    id: "17",
    title: "Ever Blue Guest House",
    slug: "stays",
    slugTitle: "Stays",
    description: "Ever Blue, Funagas Magu, Mathiveri",
    image: "/services/stay/ever blue guesthouse/01.PNG",
    phone: "7749203",
    email: "everblueguesthouse@gmail.com",
    website: " ",
  },
  {
    id: "18",
    title: "Mahchavaru Maldives",
    slug: "stays",
    slugTitle: "Stays",
    description: "Chaandhanee Magu, Mathiveri",
    image: "/services/stay/mahchavaru maldives/01.JPG",
    phone: "7782556",
    email: "fowzan.maldives@gmail.com",
    website: " ",
  },
  {
    id: "19",
    title: "Mathiveri Beach View",
    slug: "stays",
    slugTitle: "Stays",
    description: "New Heaven Nika Hingun, Mathiveri",
    image: "",
    phone: "9999389",
    email: "natture@hotmail.com",
    website: " ",
  },
  {
    id: "20",
    title: "Mathiveri Thundi Inn",
    slug: "stays",
    slugTitle: "Stays",
    description: "Ranfaru, Mathiveri",
    image: "/services/stay/mathiveri thundi inn/01.PNG",
    phone: "7784597",
    email: "ranfaruhassan@gmail.com",
    website: "www.mathiverithundiinn.com",
  },
  {
    id: "21",
    title: "Mystic Maldives",
    slug: "stays",
    slugTitle: "Stays",
    description: "Binaa, Husnuheenaa Magu, Mathiveri",
    image: "/services/stay/mystic maldives/01.JPG",
    phone: "7781434",
    email: "mysticmaldives@gmail.com",
    website: "www.mysticmaldives.com",
  },
  {
    id: "22",
    title: "Riveli Retreat",
    slug: "stays",
    slugTitle: "Stays",
    description: "Blue Reef, Mathiveri",
    image: "/services/stay/riveli retreat/01.jpg",
    phone: "7778299",
    email: "info@rivelimaldives.com",
    website: "www.rivelimaldives.com",
  },
  {
    id: "23",
    title: "Royal Reef Stay",
    slug: "stays",
    slugTitle: "Stays",
    description: "Gaskara, Mathiveri",
    image: "/services/stay/royal reef stay/01.JPG",
    phone: "9664406",
    email: "info@royalreefstay.com",
    website: "www.royalreefstay.com",
  },
  {
    id: "24",
    title: "Sands Inn",
    slug: "stays",
    slugTitle: "Stays",
    description: "Milano, Chandhanee Magu, Mathiveri",
    image: "/services/stay/sands inn/01.PNG",
    phone: "9883388",
    email: "office@maldives-inc.com",
    website: " ",
  },
  {
    id: "25",
    title: "Sis Tourist Villa",
    slug: "stays",
    slugTitle: "Stays",
    description: "Minivan Ufaa, Funagas Magu, Mathiveri",
    image: "/services/stay/sis tourist villa/01.JPG",
    phone: "9300303",
    email: "mail@sistouristvilla.com",
    website: " ",
  },
  {
    id: "26",
    title: "Sunset Beach Stay",
    slug: "stays",
    slugTitle: "Stays",
    description: "Fine Beach, Buruzu Magu, Mathiveri",
    image: "/services/stay/sunset beach stay/01.PNG",
    phone: "7544080",
    email: "mathiverisunset@gmail.com",
    website: "www.sunsetbeachstay.com",
  },
  {
    id: "27",
    title: "Vacanza Mathiveri",
    slug: "stays",
    slugTitle: "Stays",
    description: "Rienthra, Nikagas Magu, Mathiveri",
    image: "/services/stay/vacanza mathiveri/01.jpg",
    phone: "9900809",
    email: "vacanza.mathiveri@gmail.com",
    website: " ",
  },
  {
    id: "28",
    title: "Veli Beach Inn",
    slug: "stays",
    slugTitle: "Stays",
    description: "Handhuvaru, Mathiveri",
    image: "/services/stay/veli beach inn/01.JPG",
    phone: "7944345",
    email: "abbasibra.ibrahim@gmail.com",
    website: " ",
  },
];
