import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Source_Sans_3, PT_Sans } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const sans3 = Source_Sans_3({ subsets: ["latin"], weight: "400" });
const ptSans = PT_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Mathiveri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ptSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
