const navItems = [
  { name: "Home", href: "/", subItems: [] },
  {
    name: "Explore",
    href: "/explore",
    subItems: [
      { name: "Introduction", href: "#" },
      { name: "Government Institutions", href: "#" },
      { name: "Mathiveri Finolhu", href: "#" },
      { name: "People of Mathiveri", href: "#" },
      { name: "Cuisine", href: "#" },
      { name: "Landmarks & Historical Sites", href: "#" },
      { name: "Beaches", href: "#" },
      { name: "Lagoon & Coral Reefs", href: "#" },
    ],
  },
  {
    name: "Service Providers",
    href: "/services",
    subItems: [
      { name: "Stay", href: "#" },
      { name: "Dine", href: "#" },
      { name: "Gifts & Groceries", href: "#" },
      { name: "Water Sports", href: "#" },
      { name: "Diving", href: "#" },
      { name: "Excursion", href: "#" },
      { name: "Laundry Service", href: "#" },
      { name: "Photo & Video Shooting", href: "#" },
      { name: "Traditional Herbal & Spa Treatment", href: "#" },
      { name: "Hair Dressing & Makeup", href: "#" },
    ],
  },
  {
    name: "Facilities",
    href: "/facilities",
    subItems: [
      { name: "Food & Accomodation", href: "#" },
      { name: "Traveling", href: "#" },
      { name: "Water Sports & Diving", href: "#" },
      { name: "Boat Hiring & Excursion Trips", href: "#" },
      { name: "Modern medicine & Local Treatment", href: "#" },
      { name: "Hair Dressing & Spa Treatments", href: "#" },
      { name: "Land Sports", href: "#" },
      { name: "Photo & Video Shooting", href: "#" },
      { name: "ATM", href: "#" },
      { name: "Indoor & Outdoor Gym", href: "#" },
      { name: "Pharmacy", href: "#" },
      { name: "Children Park", href: "#" },
    ],
  },
  {
    name: "Occasions",
    href: "/occasions",
    subItems: [
      { name: "New Year Celebration", href: "#" },
      { name: "Eid Cultural Festival", href: "#" },
      { name: "Island Cleaning Quest", href: "#" },
      { name: "Wedding", href: "#" },
      { name: "Honeymoon", href: "#" },
      { name: "Celebrations", href: "#" },
    ],
  },
  {
    name: "Things To Do",
    href: "/things-to-do",
    subItems: [
      { name: "Canoe / Watersports", href: "#" },
      { name: "Dinner at Beach", href: "#" },
      { name: "Diving", href: "#" },
      { name: "Excursion Trips", href: "#" },
      { name: "Experiencing Local Lifestyle", href: "#" },
      { name: "Fishing", href: "#" },
      { name: "Picnic", href: "#" },
      { name: "Snorkeling", href: "#" },
      { name: "Sun Bathing", href: "#" },
    ],
  },
];
export default navItems;